# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  identify-simhub-version:
    runs-on: ubuntu-latest

    outputs:
      latest_tag: ${{ steps.fetchkeys.outputs.latest_tag }}
      download_url: ${{ steps.fetchkeys.outputs.download_url }}

    steps:
      - uses: actions/checkout@v5

      - name: Fetch latest binary
        id: fetchkeys
        continue-on-error: true
        run: |
          curl -Ls "https://api.github.com/repos/SHWotever/SimHub/releases/latest" -o latest_simhub.json
          LATEST_TAG=$(grep -Po '"tag_name": "\K[^"]*' ./latest_simhub.json)
          DOWNLOAD_URL=$(grep -Po '"browser_download_url": "\K[^"]*' ./latest_simhub.json)

          echo "Latest build: $LATEST_TAG"
          echo "Download link: $DOWNLOAD_URL"

          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest

    needs:
      - identify-simhub-version

    outputs:
      project_dlls: ${{ steps.artifact-upload-step.outputs.artifact-id }}

    env:
      SIMHUB_INSTALL_PATH: "D:\\SimHub\\"

    steps:
    - uses: actions/checkout@v5

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - uses: actions/cache@v3
      name: Restore Caches
      id: cache
      with:
        path: SimHub.${{ needs.identify-simhub-version.outputs.latest_tag }}.zip
        key: SimHub.${{ needs.identify-simhub-version.outputs.latest_tag }}

    - name: Install SimHub # Used to download the SimHub DLLs - only if not in cache.
      if: steps.cache.outputs.cache-hit != 'true'
      run: | 
        aria2c -j1 -o SimHubSetup.${{ needs.identify-simhub-version.outputs.latest_tag }}.zip "${{ needs.identify-simhub-version.outputs.download_url }}"
        7z x SimHubSetup.${{ needs.identify-simhub-version.outputs.latest_tag }}.zip -y

        New-Item -Path "D:\" -Name "SimHub" -ItemType "Directory"
        ./SimHubSetup_${{ needs.identify-simhub-version.outputs.latest_tag }}.exe /VERYSILENT /Dir="D:\SimHub"

        do {
          Write-Output "Waiting for files..."
          Start-Sleep -Seconds 5
        } until (
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}WoteverCommon.dll" -PathType Leaf) -and
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}WoteverLocalization.dll" -PathType Leaf) -and
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}GameReaderCommon.dll" -PathType Leaf) -and
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}SimHub.Logging.dll" -PathType Leaf) -and
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}SimHub.Plugins.dll" -PathType Leaf) -and
          (Test-Path -path "${{ env.SIMHUB_INSTALL_PATH }}log4net.dll" -PathType Leaf)
        )

        Start-Sleep -Seconds 3
        Write-Output "All files are found"

        Compress-Archive -Path ${{ env.SIMHUB_INSTALL_PATH }} -DestinationPath ./SimHub.${{ needs.identify-simhub-version.outputs.latest_tag }}.zip

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore NuGet Packages
      run: nuget restore OpenFFBoardPlugin.sln

    - name: Build
      run: msbuild OpenFFBoardPlugin.sln /p:Configuration=Release

    - name: Zip output DLL file
      run: |
        dir ./bin/Release/
        Compress-Archive -Path ./bin/Release/OpenFFBoardPlugin.dll -DestinationPath ./main.zip

    - name: Upload artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: build-file
        path: main.zip
