# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Release

on:
  push:
    tags: 
    - 'v*'

env:
  ReleaseFileName: OpenFFBoard.PluginSdk_${{ github.ref_name }}.zip

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv -l -s all
        env:
          OUTPUT: CHANGES.md

  create-release:
    runs-on: ubuntu-latest

    needs:
    - generate-changelog
    - build

    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: ${{ needs.build.outputs.project_dlls }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body: "${{ needs.generate-changelog.outputs.release_body }}"
        fail_on_unmatched_files: true
        files: ${{ env.ReleaseFileName }}
